# Generated by Django 2.2 on 2019-09-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0006_auto_20190911_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
